### ISSUE TITLE
Look into candles 

### ISSUE THREAD

**Issue by robcxyz** [balancednetwork/balanced-backend#31]
<img width="640" alt="image" src="https://github.com/balancednetwork/balanced-backend/assets/6512972/562ade61-09a2-46b4-90a3-eed7af41f632">

Weirdly doesn't seem to be an issue in 4 hour candles 

One other weird issue i noticed, some candles are displayed incorrectly here and there

https://app.balanced.network/trade/BALN_bnUSD

**Comment by robcxyz** [comment]
@hetfly - Hey man, I'm digging into the data but it is not obvious to me which exact lines should be red. Can you take a closer look and if the data is corrupted tell me exactly where?

**Comment by hetfly** [comment]
@robcxyz I think this is depricated issue, the new endpoint https://balanced.icon.community/api/v1/tokens has all the tokens that exist, regardless Balanced lists. Balanced token lists now serve just as a filter for displaying relevant tokens.

**Comment by hetfly** [comment]
@robcxyz looking at the picture above, the candle with the arrow should have `open` equal to the previous candle `close` value. There are also wrong values for `high` and `low`, for example here
<img width="414" alt="image" src="https://github.com/balancednetwork/balanced-backend/assets/13098459/5523bd47-b7b6-4150-b9cf-6a7fdf02c613">
the candles should never jump like that, every candle starts at the value where the previous one was closed (the thick parts). The wicks represent `high` and `low` during the given time period.

So to identify the wrong data, just check if the candle has open equal to previous candles close

Edit: Also, when the candle has wrong open and close, it seems to always have open equal to close
