### ISSUE TITLE
Update token-stats endpoint 

### ISSUE THREAD

**Issue by robcxyz** [balancednetwork/balanced-backend#32]
Please sync this endpoint https://balanced.sudoblock.io/api/v1/stats/token-stats
with these token lists:
https://github.com/balancednetwork/balanced-network-interface/blob/master/src/store/lists/communitylist.json
https://github.com/balancednetwork/balanced-network-interface/blob/master/src/store/lists/tokenlist.json

Meaning we would like to have all those tokens in the endpoint response and to have it automatically reflect newly added tokens to any of those lists.

**Comment by robcxyz** [comment]
To clarify, no real processing is needed, you just want those lists to be merged? Is this going to feed into some stats that I will need to calc?

**Comment by hetfly** [comment]
@robcxyz I think this is depricated issue, the new endpoint https://balanced.icon.community/api/v1/tokens has all the tokens that exist, regardless Balanced lists. Balanced token lists now serve just as a filter for displaying relevant tokens.

**Comment by robcxyz** [comment]
Cool - closing
