### ISSUE TITLE
Fix bnUSD supply time series

### ISSUE THREAD

**Issue by hetfly** [balancednetwork/balanced-backend#35]
on this endpoint https://balanced.icon.community/api/v1/contract-methods?skip=0&limit=1000&address=cx88fd7df7ddff82f7cc735c871dc519838cb235bb&method=totalSupply

data stop at `"days_since_launch":1000`, it's now day 1046 and bnUSD supply chart on stats page is frozen on Jan 20

**Comment by robcxyz** [comment]
https://balanced.mainnet.sng.vultr.icon.community/api/v1/contract-methods?skip=0&limit=1000&address=cx88fd7df7ddff82f7cc735c871dc519838cb235bb&method=totalSupply
