### ISSUE TITLE
Update contract volumes api to support filtering

### ISSUE THREAD

**Issue by hetfly** [balancednetwork/balanced-backend#4]
Extend the interface for getting `Events` data to support filtering through indexed positions

```
daily_volumes = [
    {
        'contract_name': 'bnusd',
        'address': addresses.BNUSD_CONTRACT_ADDRESS,
        'method': 'Transfer',
        'indexed_position': 2,
        'init_chart_time': 1619308800,
        'decimals': 1e18,
    },
   {
        'contract_name': 'loans',
        'address': addresses.LOANS_CONTRACT_ADDRESS,
        'method': 'Rebalance',
        'indexed_position': 3,
        'init_chart_time': 1619308800,
        'decimals': 1e18,
    },
]
```

-> something like this

```
daily_volumes = [
   {
        'contract_name': 'bnusd',
        'address': addresses.BNUSD_CONTRACT_ADDRESS,
        'method': 'Transfer',
        'indexed_position': 2,
        'init_chart_time': 1619308800,
        'decimals': 1e18,
        'filters': {
           '1': 'cx...',
           '2': 'cx...'
         }
    },
    {
        'contract_name': 'loans',
        'address': addresses.LOANS_CONTRACT_ADDRESS,
        'method': 'Rebalance',
        'indexed_position': 3,
        'init_chart_time': 1619308800,
        'decimals': 1e18,
        'filters': {
           '1': 'hx...'
           '3': 'cx...'
         }
    },
]
```

**Comment by robcxyz** [comment]
How about something like:

```python
    {
        'contract_name': 'loans',
        'address': addresses.LOANS_CONTRACT_ADDRESS,
        'method': 'Rebalance',
        'indexed_position': 3,
        # 'init_chart_time': 1619308800,
        'init_chart_block': 49969595,
        'decimals': 1e18,
        'filters': [
            {
                'param': 'to_address',
                'value': 'cxABC'
            },
            {
                'param': 'from_address',
                'value': 'cxABC'
            },
        ]
    },
```

In this case we are only filtering from parameters returned from the `/api/v1/logs` endpoint.  

Each filter would be a sort of `and` condition.  We could also include `or` conditions by including a `condition` field maybe which was defaulted to `and` and then optionally set it to `or` which would concatenate the output with the or condition. Might be a little more work and not worth it. 

Theoretically we could also include an `operator` field sort of like how kubernetes handles tolerations per [this document](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) where it could be one of `Equal` like k8s does it or `In` which could take a list of values to compare against. Wouldn't be too hard to implement that.

**Comment by hetfly** [comment]
Sure, makes sense, thanks! I thought we only have access to indexed position while referencing the parameters.

The additional logic with operators sounds great but I don't think there is a need for it right now. I suppose it's not too much additional work if we decide to implement it later?

**Comment by robcxyz** [comment]
I think it will be harder to implement two versions of it than just doing it right the first time IMO. 

I should ask, how many contracts do you think we are talking about?

This will not work well for filtering on all balanced related contracts BTW. For that I have to think a little more about it but in that case I think it would make most sense to include a python function as a parameter for filtering in which case the function is called with some parameters and it asserts if the Tx is supposed to be included in the result. 

I think in general, for building all wallet indexes, we should have a separate list correct? Or do you think this will be similar enough that they can share the same index / filter list?

**Comment by hetfly** [comment]
> This will not work well for filtering on all balanced related contracts BTW.

Do you mean the version with `operators`?

> I should ask, how many contracts do you think we are talking about?

I needed it only for the rebalancing (filter current user address) and specific token transfer (filter `from` and `to`). I suppose these two cases would be the majority for filtering.

> I think in general, for building all wallet indexes, we should have a separate list correct?

I think the list could be the same, depends on the filtering structure I guess. On the other hand, having a separate endpoint for volumes relating to user addresses would make sense as well. I'm sure you would make a better decision, I'm fine with both of them.

**Comment by hetfly** [comment]
@robcxyz Fez said that this is up to me now. Are we now able to filter through the historical api calls?

**Comment by robcxyz** [comment]
Filter through "historical api calls?" Can you make that more clear?

**Comment by hetfly** [comment]
Basically if happened what was discussed the initial comments. However I haven't found myself in the situation when I needed this feature now, so let's close it and we can revisit this when the need comes and reevaluate the issue based on that.
