### ISSUE TITLE
additional collateral and laon charts

### ISSUE THREAD

**Issue by hetfly** [balancednetwork/balanced-backend#49]
For these newly approved collateral tokens, duplicate the functionality of collateral debt and loans balance, BTCB endpoints for example:

https://balanced.icon.community/api/v1/contract-methods?skip=0&limit=1000&contract_name=loans_BTCB_balance
https://balanced.icon.community/api/v1/contract-methods?skip=0&limit=1000&contract_name=loans_collateral_debt_BTCB_bnusd

new tokens:

INJ - cx4297f4b63262507623b6ad575d0d8dd2db980e4e
BNB - cx2d552c485ec8bcaa75aac02424e2aca6ffdb2f1b
AVAX - cx66a031cc3bd305c76371fb586e93801b948254f0

**Comment by FezBox** [comment]
Hey @robcxyz for more clarity
![SCR-20240624-ptpm](https://github.com/balancednetwork/balanced-backend/assets/107530591/a82af0b1-c2a1-49e0-acb2-3a929652fc79)
