### ISSUE TITLE
Sync the name of renamed USDC token contract

### ISSUE THREAD

**Issue by hetfly** [balancednetwork/balanced-backend#57]
https://balanced.icon.community/api/v1/tokens

this endpoint still returns `Archway USDC` as name of the contract instead on just `USDC`

https://tracker.icon.community/contract/cx22319ac7f412f53eabe3c9827acf5e27e9c6a95f#transactions

**Comment by robcxyz** [comment]
Done

**Comment by hetfly** [comment]
It still returns Archway USDC instead of just USDC

**Comment by robcxyz** [comment]
So the symbol was synced for USDC already unless I am missing something 

For sARCH, the official name is "Liquid Finance Staked ARCH". This must have changed again recently as I had already updated it. I can change it but just want to be clear that this is a special name now and so at some point, if there are going to be a number of these overrides I'd like to put that into the code as this is going to be a theme it seems. Not a lot of work but just trying to figure out the right process as these name changes are manual now and should be kept in sync via code. 

https://tracker.icon.community/contract/cxfe94530ee0d159db3e5b7dcffbcd0dfb360075c0#contract

**Comment by hetfly** [comment]
Sorry, meant the name of `Archway USDC` to `USDC`, which is the official name now.

For sARCH, just rename it to `Staked ARCH`, if there will be others in the future we figure out the process for editing the names, but I think we're fine for now.

**Comment by robcxyz** [comment]
Ok this is done for both USDC / aARCH
