### ISSUE TITLE
Batch commits

### ISSUE THREAD

**Issue by CyrusVorwald** [balancednetwork/balanced-backend#74]
`session.commit()` should be called as bulk operations outside of loops, such as in `balanced_backend/cron/pool_stats.py`

**Comment by robcxyz** [comment]
Most of these commits that are in line with the session.add/merge were from debugging / have little performance penalty in general. 

RE pool_stats / commit outside loop - these loops generally are way too big to commit that much data outside of it. Would have memory issues.
